### ISSUE TITLE
Examples do not build when copied outside the repo

### ISSUE THREAD

**Issue by mikedotexe** [nearprotocol/near-bindgen#92] opened 2020-02-20 23:09 UTC
**Issue**
When I clone the entire near-bindgen repo and enter `examples/fun-token` and run `./build.sh` it builds correctly.
But I ran into issues when I try to copy that particular example to a separate folder.

**Motivation**
I would like users new to NEAR to be able to download small, individual examples of Rust smart contracts and have them build as expected. I do not want them to have to clone the `near-bindgen` repo and build the examples from there.

**Steps to reproduce**:
Copy `examples/fun-token` into somewhere locally `~/tmp/` or something.
Swap out this line:
https://github.com/nearprotocol/near-bindgen/blob/master/examples/fun-token/Cargo.toml#L13
with:
near-bindgen = "0.4.1" (which is the same version)
Go to `~/tmp/fun-token` and run `./build` 
It will throw errors relating to panic() wanting bytes.

**Comment by nearmax** [comment] 2020-02-20 23:15
Caused by #53 which merged into master without building a new version.

**Comment by nearmax** [comment] 2020-02-20 23:34
Verified by @mikedotexe to be working.

**Closed by nearmax** 2020-02-20 23:34 UTC
Labels: P0, bug
